version: '3.8'

services:
  postgresql-master:
    image: "bitnami/postgresql:16"
    ports:
      - "5433:5432"  # Changed host port to 5433 to avoid conflict
    volumes:
      - "./postgresql_master_data:/bitnami/postgresql"  # Volume path for master
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=root-user
      - POSTGRESQL_PASSWORD=StrongPassword134
      - POSTGRESQL_DATABASE=INSA_psychometry_v2
      - ALLOW_EMPTY_PASSWORD=yes

  postgresql-slave:
    image: "bitnami/postgresql:16"
    ports:
      - "5434:5432"  # Changed host port to 5434 to avoid conflict
    depends_on:
      - postgresql-master
    volumes:
      - "./postgresql_slave_data:/bitnami/postgresql"  # Volume path for slave
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8085:80/tcp"  # Changed host port to 8085 to avoid conflict
    volumes:
      - "./pgadmin_data:/var/lib/pgadmin"  # Volume path for pgAdmin
    environment:
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_DEFAULT_EMAIL=mernat777@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    depends_on:
      - postgresql-master
    tty: true